### ISSUE TITLE
Updating properties of the openstack integrator charm do not propagate automatically

### ISSUE THREAD

**Issue by CalvinHartwell** [juju-solutions/charm-openstack-integrator#10]
Hi all,

The open stack integrator charm works well, load-balancers and storage through cinder can be created. However, if you accidentally get the floating-network-id or subnet-id incorrect, they cannot be changed after deployment right now. If you attempt to update them by changing the charm config or by redeploying the bundle with updated values, they are ignored.

Set these values in the bundle: 

```
  openstack-integrator:
    charm: cs:~containers/openstack-integrator
    num_units: 1
    options:
      #endpoint-tls-ca: include-base64:///home/ubuntu/openstack-ca.crt
      password: <CATS-ARE-GOD>
      project-domain-name: admin_domain
      user-domain-name: admin_domain
      username: admin
      project-name: admin
      region: RegionOne
      auth-url: http://172.16.7.18:5000/v3
      subnet-id: 21ab2f91-9453-4047-a27d-b364a1d0593d
      floating-network-id: 06adf264-0048-4ef5-b2f2-1bbeaf48868d
      manage-security-groups: true
```

...and then change one of the values:

```
  openstack-integrator:
    charm: cs:~containers/openstack-integrator
    num_units: 1
    options:
      #endpoint-tls-ca: include-base64:///home/ubuntu/openstack-ca.crt
      password:  <CATS-ARE-GOD>
      project-domain-name: admin_domain
      user-domain-name: admin_domain
      username: admin
      project-name: admin
      region: RegionOne
      auth-url: http://172.16.7.18:5000/v3
      subnet-id: 21ab2f91-9453-4047-a27d-b364a1d0593d
      floating-network-id: kittensarecute
      manage-security-groups: true
```

I assume other properties probably can't be updated either, but we hit this issue with the floating-network-id. The others should also be tested, in case the user picks the wrong value. 

Many thanks!
